version: '3'

services:
        app:
            container_name: finizens_app
            build:
                context: ./docker/app
                args:
                    - timezone=${TZ}
            volumes:
                - ./symfony:/var/www/html:rw,cached
            env_file:
                - .env
            environment:
                XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST}
                PHP_IDE_CONFIG: serverName=${NGINX_HOST}

        nginx:
            container_name: finizens_nginx
            build:
                context: ./docker/nginx
                args:
                    - nginx_host=${NGINX_HOST}
            ports:
                - "8008:80"
                - "443:443"
            depends_on:
                - app
            volumes:
                - ./symfony/public:/var/www/html/public:ro
                - ./docker/nginx/default.template:/etc/nginx/conf.d/default.template
                - nginx_log:/var/log/nginx
            env_file:
                - .env
            command: /bin/bash -c "envsubst '$$NGINX_HOST'
                < /etc/nginx/conf.d/default.template
                > /etc/nginx/conf.d/default.conf
                && exec nginx -g 'daemon off;'"

volumes:
    nginx_log:
